# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/
theme = "congo"
baseURL = "https://dungpb.com/"
defaultContentLanguage = "en"
googleAnalytics = "G-38ZLQ4M1VD"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]